name: Build and Release APK

on:
  workflow_dispatch:

env:
  main_project_module: app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK (unsigned)
        run: ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Rename APK file
        run: |
          OLD_PATH="app/build/outputs/apk/release/app-release-unsigned.apk"
          NEW_PATH="app/build/outputs/apk/release/adbport-release-unsigned.apk"
          if [ -f "$OLD_PATH" ]; then
            mv "$OLD_PATH" "$NEW_PATH"
          else
            echo "Error: Release APK not found"
            exit 1
          fi

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: adbport-release-unsigned
          path: app/build/outputs/apk/release/adbport-release-unsigned.apk
